const VISTOR_ROOM = "ROOM-VISITOR";
const SECURE_ROOM = "ROOM-SECURE";
const ROOM_LIMIT = 15000;
const SECURE_ROOM_LIMIT = 200;
const NOTIFICATION_ROOM = "ROOM-NOTIFY";
const SEND_SMS_TEMPLATE_ID = "1707162401207175175";

const SALT_ROUND = 10;
module.exports = {
    VISTOR_ROOM,
    SECURE_ROOM,
    ROOM_LIMIT,
    SECURE_ROOM_LIMIT,
    NOTIFICATION_ROOM,
    SALT_ROUND,
    SEND_SMS_TEMPLATE_ID
};
